CREATE TABLE CRACK_DISPLACEMENTS (
    UID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    PROJECT_ID INTEGER,
    DEVICE_TYPE VARCHAR(50),
    DEVICE_ID VARCHAR(50),
    DATUM_UND_UHRZEIT TIMESTAMP,
    TEMP_MESSWERTE_01 FLOAT,
    RELF_MESSWERTE_01 FLOAT,
    RISS_MESSWERTE_01 FLOAT,
    U1_MESSWERTE_01 FLOAT,
    U2_MESSWERTE_01 FLOAT,
    U3_MESSWERTE_01 FLOAT,
    U4_MESSWERTE_01 FLOAT,
    DUMMY FLOAT) ORGANIZE BY ROW;
