CREATE TABLE DEVICE_META (
    M_TIMESTAMP TIMESTAMP,
    UNIT_OF_MEASUREMENT VARCHAR(50),
    DEVICE_ID VARCHAR(50),
    DEVICE_TYPE VARCHAR(50),
    FIRST_MEASUREMENT FLOAT,
    ID INTEGER NOT NULL,
    LOCATION_BLOCK VARCHAR(50),
    LOCATION_STAGE VARCHAR(50),
    LOCATION_SECTION VARCHAR(50),
    LOCATION_SUBSECTION VARCHAR(50),
    ALERTLEVEL_ID INTEGER,
    PRIMARY KEY (ID)
) ORGANIZE BY ROW;